// export const URL = "http://hongguang.club:3005/api"
export const URL = "http://localhost:3005/api"
export const secret = "ahstuEpicWHG"
export const YiBanAuth = "https://openapi.yiban.cn/oauth/authorize"
export const CLIENTID = "891cfb29de4a0fbe"
export const REDIRECTURL = URL + "/user/auth"